export const customerData = [
  {
    name: 'John Doe',
    email: 'john.doe@example.com',
    phone: '555-1234',
    totalSpent: 500,
    city: 'New York',
    address: '123 Main St',
    pinCode: '10001',
    district: 'Manhattan',
    state: 'New York',
  },
  {
    name: 'Jane Smith',
    email: 'jane.smith@example.com',
    phone: '555-5678',
    totalSpent: 800,
    city: 'Los Angeles',
    address: '456 Elm St',
    pinCode: '90001',
    district: 'Los Angeles',
    state: 'California',
  },
  {
    name: 'Bob Johnson',
    email: 'bob.johnson@example.com',
    phone: '555-9876',
    totalSpent: 300,
    city: 'Chicago',
    address: '789 Oak St',
    pinCode: '60601',
    district: 'Cook',
    state: 'Illinois',
  },
  {
    name: 'Alice Williams',
    email: 'alice.williams@example.com',
    phone: '555-4321',
    totalSpent: 1200,
    city: 'Houston',
    address: '101 Pine St',
    pinCode: '77002',
    district: 'Harris',
    state: 'Texas',
  },
  {
    name: 'Charlie Brown',
    email: 'charlie.brown@example.com',
    phone: '555-6543',
    totalSpent: 700,
    city: 'San Francisco',
    address: '321 Cedar St',
    pinCode: '94101',
    district: 'San Francisco',
    state: 'California',
  },
  {
    name: 'Jane Smith',
    email: 'jane.smith@example.com',
    phone: '555-5678',
    totalSpent: 800,
    city: 'Los Angeles',
    address: '456 Elm St',
    pinCode: '90001',
    district: 'Los Angeles',
    state: 'California',
  },
  {
    name: 'Bob Johnson',
    email: 'bob.johnson@example.com',
    phone: '555-9876',
    totalSpent: 300,
    city: 'Chicago',
    address: '789 Oak St',
    pinCode: '60601',
    district: 'Cook',
    state: 'Illinois',
  },
  {
    name: 'Alice Williams',
    email: 'alice.williams@example.com',
    phone: '555-4321',
    totalSpent: 1200,
    city: 'Houston',
    address: '101 Pine St',
    pinCode: '77002',
    district: 'Harris',
    state: 'Texas',
  },
  {
    name: 'Charlie Brown',
    email: 'charlie.brown@example.com',
    phone: '555-6543',
    totalSpent: 700,
    city: 'San Francisco',
    address: '321 Cedar St',
    pinCode: '94101',
    district: 'San Francisco',
    state: 'California',
  },
  {
    name: 'Jane Smith',
    email: 'jane.smith@example.com',
    phone: '555-5678',
    totalSpent: 800,
    city: 'Los Angeles',
    address: '456 Elm St',
    pinCode: '90001',
    district: 'Los Angeles',
    state: 'California',
  },
  {
    name: 'Bob Johnson',
    email: 'bob.johnson@example.com',
    phone: '555-9876',
    totalSpent: 300,
    city: 'Chicago',
    address: '789 Oak St',
    pinCode: '60601',
    district: 'Cook',
    state: 'Illinois',
  },
  {
    name: 'Alice Williams',
    email: 'alice.williams@example.com',
    phone: '555-4321',
    totalSpent: 1200,
    city: 'Houston',
    address: '101 Pine St',
    pinCode: '77002',
    district: 'Harris',
    state: 'Texas',
  },
  {
    name: 'Charlie Brown',
    email: 'charlie.brown@example.com',
    phone: '555-6543',
    totalSpent: 700,
    city: 'San Francisco',
    address: '321 Cedar St',
    pinCode: '94101',
    district: 'San Francisco',
    state: 'California',
  },
];